// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apichat/internal/conf"
	"apichat/internal/server"
	"apichat/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	log2 "github.com/gomicroim/gomicroim/pkg/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discover *conf.Discover, logger log.Logger, logLogger *log2.Logger, discovery registry.Discovery) (*kratos.App, func(), error) {
	chatClient := service.NewChatClient(discover, discovery)
	chatService := service.NewChatService(chatClient)
	httpServer := server.NewHTTPServer(confServer, chatService, logger)
	app := newApp(logLogger, httpServer)
	return app, func() {
	}, nil
}
