#
# docker compose 服务编排
#

version: '3.4'

services:
  rpc-timeline: # 实现的扩散写timeline服务
    image: "xmcy0011/go-timeline:latest"
    container_name: rpc-timeline
    volumes:
      - ./deploy/docker/configs:/data/conf
    environment:
      - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - goMicroIM
    ports:
      - "9321:8000"
      - "9322:9000"
  rpc-user:
    container_name: rpc-user
    build: # 指定从dockerfile编译
      context: .
      dockerfile: ./template.rpc.Dockerfile
      args:
        app: user
    volumes:
      - ./deploy/docker/configs:/data/conf
    environment:
      - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - goMicroIM
    ports:
      - "9100:9000"
  rpc-chat:
    container_name: rpc-chat
    build: # 指定从dockerfile编译
      context: .
      dockerfile: ./template.rpc.Dockerfile
      args:
        app: chat
    volumes:
      - ./deploy/docker/configs:/data/conf
    environment:
      - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - goMicroIM
    ports:
      - "9101:9000"
  rpc-push-job:
    container_name: rpc-push-job
    build:
      context: .
      dockerfile: ./template.rpc.Dockerfile
      args:
        app: pushjob
    volumes:
      - ./deploy/docker/configs:/data/conf
    environment:
      - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - goMicroIM
    ports:
      - "9102:9000"
  api-gw:
    container_name: api-gw
    build:
      context: .
      dockerfile: ./template.api.Dockerfile
      args:
        app: apigw
    volumes:
      - ./deploy/docker/configs:/data/conf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - TZ=Asia/Shanghai
    networks:
      - goMicroIM
    ports:
      - "8100:8000"
    depends_on:
      - rpc-user
      - rpc-chat
  ws-push:
    container_name: ws-push
    build:
      context: .
      dockerfile: ./template.api.Dockerfile
      args:
        app: wspush
    volumes:
      - ./deploy/docker/configs:/data/conf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - TZ=Asia/Shanghai
    networks:
      - goMicroIM
    ports:
      - "8102:8000"
    depends_on:
      - rpc-user
networks:
  goMicroIM:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1