server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
data:
  database:
    driver: mysql
    source: cim:coffeechat2022@tcp(mysql:3306)/coffeechat?charset=utf8mb4&parseTime=true
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
discover:
  etcd:
    endpoints: [ etcd:2379 ]
  service_endpoint:
    rpc_user: rpc-user