// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chat/internal/biz"
	"chat/internal/conf"
	"chat/internal/data"
	"chat/internal/data/cache"
	"chat/internal/mq"
	"chat/internal/server"
	"chat/internal/service"
	"github.com/go-kratos/kratos/contrib/registry/etcd/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	log2 "github.com/gomicroim/gomicroim/pkg/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confServer *conf.Server, confData *conf.Data, data_Kafka *conf.Data_Kafka, logger log.Logger, logLogger *log2.Logger, registry *etcd.Registry) (*kratos.App, func(), error) {
	client, err := data.NewEntClient(confData)
	if err != nil {
		return nil, nil, err
	}
	redisClient, err := data.NewRedis(confData, logLogger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(logLogger, client, redisClient)
	if err != nil {
		return nil, nil, err
	}
	messageRepo := data.NewMessageRepo(dataData, logLogger)
	msgSeq := cache.NewMsgSeq(redisClient)
	sessionRepo := data.NewSessionRepo(dataData, logLogger)
	messageHistoryUseCase := biz.NewMessageHistoryUseCase(messageRepo, msgSeq, sessionRepo)
	msgProducer := mq.NewMsgProducer(data_Kafka)
	chatConsumerGroup := mq.NewChatConsumerGroup(data_Kafka)
	messageSyncUseCase := biz.NewMessageSyncUseCase(bootstrap, logLogger, msgProducer, chatConsumerGroup)
	recentSessionUseCase := biz.NewRecentSessionUseCase(sessionRepo)
	chatService := service.NewChatService(messageHistoryUseCase, messageSyncUseCase, recentSessionUseCase, logLogger, chatConsumerGroup, msgProducer)
	sessionService := service.NewSessionService(recentSessionUseCase)
	msgListService := service.NewMsgListService(messageHistoryUseCase)
	grpcServer := server.NewGRPCServer(confServer, chatService, sessionService, msgListService, logger)
	app := newApp(logger, bootstrap, grpcServer, registry, chatConsumerGroup)
	return app, func() {
		cleanup()
	}, nil
}
