// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: protos/chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息信息
type IMMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *IMMsg_From `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // 来源用户信息
	Peer *IMMsg_Peer `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"` // 目标群组或个人信息
	// 消息内容
	MsgType IMMsgType  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=chat.IMMsgType" json:"msg_type,omitempty"` // 消息类型
	MsgData *anypb.Any `protobuf:"bytes,4,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`                      // 消息内容，根据 msg_type 动态变化
	// 高级
	MsgId      string       `protobuf:"bytes,10,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                        // 消息唯一ID（UUID，由客户端产生）
	MsgSeq     int64        `protobuf:"varint,11,opt,name=msg_seq,json=msgSeq,proto3" json:"msg_seq,omitempty"`                                    // 消息序号，在同一个会话中唯一且连续递增
	MsgResCode IMResCode    `protobuf:"varint,12,opt,name=msg_res_code,json=msgResCode,proto3,enum=chat.IMResCode" json:"msg_res_code,omitempty"`  // 消息错误码
	MsgFeature IMMsgFeature `protobuf:"varint,13,opt,name=msg_feature,json=msgFeature,proto3,enum=chat.IMMsgFeature" json:"msg_feature,omitempty"` // 消息属性
	MsgStatus  IMMsgStatus  `protobuf:"varint,14,opt,name=msg_status,json=msgStatus,proto3,enum=chat.IMMsgStatus" json:"msg_status,omitempty"`     // 消息状态（预留）
	CreateTime int64        `protobuf:"varint,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                        // 消息创建时间戳（毫秒）
}

func (x *IMMsg) Reset() {
	*x = IMMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg) ProtoMessage() {}

func (x *IMMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg.ProtoReflect.Descriptor instead.
func (*IMMsg) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *IMMsg) GetFrom() *IMMsg_From {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *IMMsg) GetPeer() *IMMsg_Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *IMMsg) GetMsgType() IMMsgType {
	if x != nil {
		return x.MsgType
	}
	return IMMsgType_MsgTypeUnknown
}

func (x *IMMsg) GetMsgData() *anypb.Any {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *IMMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *IMMsg) GetMsgSeq() int64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *IMMsg) GetMsgResCode() IMResCode {
	if x != nil {
		return x.MsgResCode
	}
	return IMResCode_ResCodeUnknown
}

func (x *IMMsg) GetMsgFeature() IMMsgFeature {
	if x != nil {
		return x.MsgFeature
	}
	return IMMsgFeature_MsgFeatureDefault
}

func (x *IMMsg) GetMsgStatus() IMMsgStatus {
	if x != nil {
		return x.MsgStatus
	}
	return IMMsgStatus_MsgStatusNone
}

func (x *IMMsg) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 会话信息
type IMSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId     int64         `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                               // 会话id
	SessionType   IMSessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=chat.IMSessionType" json:"session_type,omitempty"` // 会话类型
	UnreadCnt     int32         `protobuf:"varint,4,opt,name=unread_cnt,json=unreadCnt,proto3" json:"unread_cnt,omitempty"`                               // 该会话未读消息数量
	UpdatedTime   int32         `protobuf:"varint,5,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`                         // 更新时间
	MsgUuid       string        `protobuf:"bytes,6,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`                                      // 最新一条消息的id（UUID）
	MsgSeq        int64         `protobuf:"varint,7,opt,name=msg_seq,json=msgSeq,proto3" json:"msg_seq,omitempty"`                                        // 最新一条消息服务端的id（顺序递增）
	MsgTimeStamp  int32         `protobuf:"varint,8,opt,name=msg_time_stamp,json=msgTimeStamp,proto3" json:"msg_time_stamp,omitempty"`                    // 最新一条消息时间戳（毫秒）
	MsgData       []byte        `protobuf:"bytes,9,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`                                      // 最新一条消息的内容
	MsgType       IMMsgType     `protobuf:"varint,10,opt,name=msg_type,json=msgType,proto3,enum=chat.IMMsgType" json:"msg_type,omitempty"`                // 最新一条消息的类型
	MsgFromUserId int64         `protobuf:"varint,11,opt,name=msg_from_user_id,json=msgFromUserId,proto3" json:"msg_from_user_id,omitempty"`              // 最新一条消息的发送者
	MsgStatus     IMMsgStatus   `protobuf:"varint,12,opt,name=msg_status,json=msgStatus,proto3,enum=chat.IMMsgStatus" json:"msg_status,omitempty"`        // 最新一条消息的状态（预留）
	MsgAttach     *string       `protobuf:"bytes,13,opt,name=msg_attach,json=msgAttach,proto3,oneof" json:"msg_attach,omitempty"`                         // 最新一条消息的附件（预留）
	ExtendData    *string       `protobuf:"bytes,14,opt,name=extend_data,json=extendData,proto3,oneof" json:"extend_data,omitempty"`                      // 本地扩展字段（限制4096）
}

func (x *IMSession) Reset() {
	*x = IMSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMSession) ProtoMessage() {}

func (x *IMSession) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMSession.ProtoReflect.Descriptor instead.
func (*IMSession) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *IMSession) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *IMSession) GetSessionType() IMSessionType {
	if x != nil {
		return x.SessionType
	}
	return IMSessionType_SessionTypeInvalid
}

func (x *IMSession) GetUnreadCnt() int32 {
	if x != nil {
		return x.UnreadCnt
	}
	return 0
}

func (x *IMSession) GetUpdatedTime() int32 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *IMSession) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *IMSession) GetMsgSeq() int64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *IMSession) GetMsgTimeStamp() int32 {
	if x != nil {
		return x.MsgTimeStamp
	}
	return 0
}

func (x *IMSession) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *IMSession) GetMsgType() IMMsgType {
	if x != nil {
		return x.MsgType
	}
	return IMMsgType_MsgTypeUnknown
}

func (x *IMSession) GetMsgFromUserId() int64 {
	if x != nil {
		return x.MsgFromUserId
	}
	return 0
}

func (x *IMSession) GetMsgStatus() IMMsgStatus {
	if x != nil {
		return x.MsgStatus
	}
	return IMMsgStatus_MsgStatusNone
}

func (x *IMSession) GetMsgAttach() string {
	if x != nil && x.MsgAttach != nil {
		return *x.MsgAttach
	}
	return ""
}

func (x *IMSession) GetExtendData() string {
	if x != nil && x.ExtendData != nil {
		return *x.ExtendData
	}
	return ""
}

// 基础属性
type IMMsg_From struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
}

func (x *IMMsg_From) Reset() {
	*x = IMMsg_From{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_From) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_From) ProtoMessage() {}

func (x *IMMsg_From) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_From.ProtoReflect.Descriptor instead.
func (*IMMsg_From) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IMMsg_From) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IMMsg_From) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type IMMsg_Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionType IMSessionType `protobuf:"varint,1,opt,name=session_type,json=sessionType,proto3,enum=chat.IMSessionType" json:"session_type,omitempty"` // 会话类型
	PeerId      string        `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                                         // 目标会话ID
	PeerName    *string       `protobuf:"bytes,3,opt,name=peer_name,json=peerName,proto3,oneof" json:"peer_name,omitempty"`                             // 目标名称，发消息时无需指定
}

func (x *IMMsg_Peer) Reset() {
	*x = IMMsg_Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_Peer) ProtoMessage() {}

func (x *IMMsg_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_Peer.ProtoReflect.Descriptor instead.
func (*IMMsg_Peer) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IMMsg_Peer) GetSessionType() IMSessionType {
	if x != nil {
		return x.SessionType
	}
	return IMSessionType_SessionTypeInvalid
}

func (x *IMMsg_Peer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *IMMsg_Peer) GetPeerName() string {
	if x != nil && x.PeerName != nil {
		return *x.PeerName
	}
	return ""
}

type IMMsg_MsgDataMix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text     *IMMsg_MsgText    `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ImgUrl   []*IMMsg_MsgImg   `protobuf:"bytes,2,rep,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	VideoUrl []*IMMsg_MsgVideo `protobuf:"bytes,3,rep,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
}

func (x *IMMsg_MsgDataMix) Reset() {
	*x = IMMsg_MsgDataMix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgDataMix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgDataMix) ProtoMessage() {}

func (x *IMMsg_MsgDataMix) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgDataMix.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgDataMix) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 2}
}

func (x *IMMsg_MsgDataMix) GetText() *IMMsg_MsgText {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *IMMsg_MsgDataMix) GetImgUrl() []*IMMsg_MsgImg {
	if x != nil {
		return x.ImgUrl
	}
	return nil
}

func (x *IMMsg_MsgDataMix) GetVideoUrl() []*IMMsg_MsgVideo {
	if x != nil {
		return x.VideoUrl
	}
	return nil
}

type IMMsg_MsgText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *IMMsg_MsgText) Reset() {
	*x = IMMsg_MsgText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgText) ProtoMessage() {}

func (x *IMMsg_MsgText) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgText.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgText) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 3}
}

func (x *IMMsg_MsgText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IMMsg_MsgImg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumbnail string `protobuf:"bytes,1,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"` // 缩略图url
	Url       string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`             // 完整图片url
	Width     int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`        // 图片原始宽
	Height    int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`      // 图片原始高
}

func (x *IMMsg_MsgImg) Reset() {
	*x = IMMsg_MsgImg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgImg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgImg) ProtoMessage() {}

func (x *IMMsg_MsgImg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgImg.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgImg) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 4}
}

func (x *IMMsg_MsgImg) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *IMMsg_MsgImg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IMMsg_MsgImg) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *IMMsg_MsgImg) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type IMMsg_MsgAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsg_MsgAudio) Reset() {
	*x = IMMsg_MsgAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgAudio) ProtoMessage() {}

func (x *IMMsg_MsgAudio) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgAudio.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgAudio) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 5}
}

type IMMsg_MsgVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsg_MsgVideo) Reset() {
	*x = IMMsg_MsgVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgVideo) ProtoMessage() {}

func (x *IMMsg_MsgVideo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgVideo.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgVideo) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 6}
}

type IMMsg_MsgFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsg_MsgFile) Reset() {
	*x = IMMsg_MsgFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgFile) ProtoMessage() {}

func (x *IMMsg_MsgFile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgFile.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgFile) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 7}
}

type IMMsg_MsgLocal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsg_MsgLocal) Reset() {
	*x = IMMsg_MsgLocal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgLocal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgLocal) ProtoMessage() {}

func (x *IMMsg_MsgLocal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgLocal.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgLocal) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 8}
}

type IMMsg_MsgTips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsg_MsgTips) Reset() {
	*x = IMMsg_MsgTips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_chat_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsg_MsgTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsg_MsgTips) ProtoMessage() {}

func (x *IMMsg_MsgTips) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsg_MsgTips.ProtoReflect.Descriptor instead.
func (*IMMsg_MsgTips) Descriptor() ([]byte, []int) {
	return file_protos_chat_chat_proto_rawDescGZIP(), []int{0, 9}
}

var File_protos_chat_chat_proto protoreflect.FileDescriptor

var file_protos_chat_chat_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x25,
	0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x68,
	0x61, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbc, 0x07, 0x0a, 0x05, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x73,
	0x67, 0x53, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x49, 0x4d, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x6d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x0a, 0x6d, 0x73, 0x67, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x0a,
	0x6d, 0x73, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x09, 0x6d, 0x73, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a,
	0x3c, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x87, 0x01,
	0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x70, 0x65,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x95, 0x01, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x69, 0x78, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x2b, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73,
	0x67, 0x49, 0x6d, 0x67, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x09,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x1a,
	0x1d, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x66,
	0x0a, 0x06, 0x4d, 0x73, 0x67, 0x49, 0x6d, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x1a, 0x0a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x1a, 0x09,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x0a, 0x0a, 0x08, 0x4d, 0x73, 0x67,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x1a, 0x09, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x70, 0x73,
	0x22, 0x89, 0x04, 0x0a, 0x09, 0x49, 0x4d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x36, 0x0a,
	0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x63, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x43, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0e, 0x6d,
	0x73, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x08,
	0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6d, 0x73, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x0a, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x4d, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x6d, 0x73, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x73, 0x67, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x73, 0x67, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x42, 0x5e, 0x0a, 0x1d,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x69, 0x6d, 0x2e, 0x6c, 0x69,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x42, 0x0c, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x69,
	0x6d, 0x2f, 0x67, 0x6f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x69, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_chat_chat_proto_rawDescOnce sync.Once
	file_protos_chat_chat_proto_rawDescData = file_protos_chat_chat_proto_rawDesc
)

func file_protos_chat_chat_proto_rawDescGZIP() []byte {
	file_protos_chat_chat_proto_rawDescOnce.Do(func() {
		file_protos_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_chat_chat_proto_rawDescData)
	})
	return file_protos_chat_chat_proto_rawDescData
}

var file_protos_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_chat_chat_proto_goTypes = []interface{}{
	(*IMMsg)(nil),            // 0: chat.IMMsg
	(*IMSession)(nil),        // 1: chat.IMSession
	(*IMMsg_From)(nil),       // 2: chat.IMMsg.From
	(*IMMsg_Peer)(nil),       // 3: chat.IMMsg.Peer
	(*IMMsg_MsgDataMix)(nil), // 4: chat.IMMsg.MsgDataMix
	(*IMMsg_MsgText)(nil),    // 5: chat.IMMsg.MsgText
	(*IMMsg_MsgImg)(nil),     // 6: chat.IMMsg.MsgImg
	(*IMMsg_MsgAudio)(nil),   // 7: chat.IMMsg.MsgAudio
	(*IMMsg_MsgVideo)(nil),   // 8: chat.IMMsg.MsgVideo
	(*IMMsg_MsgFile)(nil),    // 9: chat.IMMsg.MsgFile
	(*IMMsg_MsgLocal)(nil),   // 10: chat.IMMsg.MsgLocal
	(*IMMsg_MsgTips)(nil),    // 11: chat.IMMsg.MsgTips
	(IMMsgType)(0),           // 12: chat.IMMsgType
	(*anypb.Any)(nil),        // 13: google.protobuf.Any
	(IMResCode)(0),           // 14: chat.IMResCode
	(IMMsgFeature)(0),        // 15: chat.IMMsgFeature
	(IMMsgStatus)(0),         // 16: chat.IMMsgStatus
	(IMSessionType)(0),       // 17: chat.IMSessionType
}
var file_protos_chat_chat_proto_depIdxs = []int32{
	2,  // 0: chat.IMMsg.from:type_name -> chat.IMMsg.From
	3,  // 1: chat.IMMsg.peer:type_name -> chat.IMMsg.Peer
	12, // 2: chat.IMMsg.msg_type:type_name -> chat.IMMsgType
	13, // 3: chat.IMMsg.msg_data:type_name -> google.protobuf.Any
	14, // 4: chat.IMMsg.msg_res_code:type_name -> chat.IMResCode
	15, // 5: chat.IMMsg.msg_feature:type_name -> chat.IMMsgFeature
	16, // 6: chat.IMMsg.msg_status:type_name -> chat.IMMsgStatus
	17, // 7: chat.IMSession.session_type:type_name -> chat.IMSessionType
	12, // 8: chat.IMSession.msg_type:type_name -> chat.IMMsgType
	16, // 9: chat.IMSession.msg_status:type_name -> chat.IMMsgStatus
	17, // 10: chat.IMMsg.Peer.session_type:type_name -> chat.IMSessionType
	5,  // 11: chat.IMMsg.MsgDataMix.text:type_name -> chat.IMMsg.MsgText
	6,  // 12: chat.IMMsg.MsgDataMix.img_url:type_name -> chat.IMMsg.MsgImg
	8,  // 13: chat.IMMsg.MsgDataMix.video_url:type_name -> chat.IMMsg.MsgVideo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_chat_chat_proto_init() }
func file_protos_chat_chat_proto_init() {
	if File_protos_chat_chat_proto != nil {
		return
	}
	file_protos_chat_constant_proto_init()
	file_protos_chat_error_reason_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_chat_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_From); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgDataMix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgImg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgLocal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_chat_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsg_MsgTips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_chat_chat_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_protos_chat_chat_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_chat_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_chat_chat_proto_goTypes,
		DependencyIndexes: file_protos_chat_chat_proto_depIdxs,
		MessageInfos:      file_protos_chat_chat_proto_msgTypes,
	}.Build()
	File_protos_chat_chat_proto = out.File
	file_protos_chat_chat_proto_rawDesc = nil
	file_protos_chat_chat_proto_goTypes = nil
	file_protos_chat_chat_proto_depIdxs = nil
}
