server:
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
  jwt:
    access_secret: "i love im"
    refresh_secret: "u love im"
data:
  database:
    driver: mysql
    source: cim:coffeechat2022@tcp(127.0.0.1:3306)/coffeechat?charset=utf8mb4&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    password: "coffeechat"
    db: 0
    read_timeout: 0.4s
    write_timeout: 0.6s
    dial_timeout: 1s
registry:
  etcd:
    endpoints: [ 127.0.0.1:2379 ]
    register_server_name: rpc-user
    # 注册的 Endpoint，不指定默认使用本机IP
    register_end_point: ""