// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat/internal/data/ent/message"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Message is the model entity for the Message schema.
type Message struct {
	config `json:"-"`
	// ID of the ent.
	// 自增ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	Created time.Time `json:"created,omitempty"`
	// 更新时间
	Updated time.Time `json:"updated,omitempty"`
	// session唯一标志
	SessionKey string `json:"sessionKey,omitempty"`
	// 发送人Id
	From int64 `json:"from,omitempty"`
	// 接收目标ID
	To string `json:"to,omitempty"`
	// 会话类型，0:未知 1:单聊 2:群聊
	SessionType int8 `json:"session_type,omitempty"`
	// 客户端生成的消息UUID(去重)
	ClientMsgID string `json:"client_msg_id,omitempty"`
	// 服务端生成的消息序号(乱序处理)
	ServerMsgSeq int64 `json:"server_msg_seq,omitempty"`
	// 消息类型
	MsgType int8 `json:"msg_type,omitempty"`
	// 消息内容
	MsgData string `json:"msg_data,omitempty"`
	// 消息错误码
	MsgResCode int8 `json:"msg_res_code,omitempty"`
	// 消息属性
	MsgFeature int8 `json:"msg_feature,omitempty"`
	// 消息状态
	MsgStatus int8 `json:"msg_status,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Message) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case message.FieldID, message.FieldFrom, message.FieldSessionType, message.FieldServerMsgSeq, message.FieldMsgType, message.FieldMsgResCode, message.FieldMsgFeature, message.FieldMsgStatus:
			values[i] = new(sql.NullInt64)
		case message.FieldSessionKey, message.FieldTo, message.FieldClientMsgID, message.FieldMsgData:
			values[i] = new(sql.NullString)
		case message.FieldCreated, message.FieldUpdated:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Message", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Message fields.
func (m *Message) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case message.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int64(value.Int64)
		case message.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				m.Created = value.Time
			}
		case message.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				m.Updated = value.Time
			}
		case message.FieldSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sessionKey", values[i])
			} else if value.Valid {
				m.SessionKey = value.String
			}
		case message.FieldFrom:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from", values[i])
			} else if value.Valid {
				m.From = value.Int64
			}
		case message.FieldTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to", values[i])
			} else if value.Valid {
				m.To = value.String
			}
		case message.FieldSessionType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_type", values[i])
			} else if value.Valid {
				m.SessionType = int8(value.Int64)
			}
		case message.FieldClientMsgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_msg_id", values[i])
			} else if value.Valid {
				m.ClientMsgID = value.String
			}
		case message.FieldServerMsgSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field server_msg_seq", values[i])
			} else if value.Valid {
				m.ServerMsgSeq = value.Int64
			}
		case message.FieldMsgType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field msg_type", values[i])
			} else if value.Valid {
				m.MsgType = int8(value.Int64)
			}
		case message.FieldMsgData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field msg_data", values[i])
			} else if value.Valid {
				m.MsgData = value.String
			}
		case message.FieldMsgResCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field msg_res_code", values[i])
			} else if value.Valid {
				m.MsgResCode = int8(value.Int64)
			}
		case message.FieldMsgFeature:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field msg_feature", values[i])
			} else if value.Valid {
				m.MsgFeature = int8(value.Int64)
			}
		case message.FieldMsgStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field msg_status", values[i])
			} else if value.Valid {
				m.MsgStatus = int8(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Message.
// Note that you need to call Message.Unwrap() before calling this method if this Message
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Message) Update() *MessageUpdateOne {
	return (&MessageClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the Message entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Message) Unwrap() *Message {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Message is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Message) String() string {
	var builder strings.Builder
	builder.WriteString("Message(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("created=")
	builder.WriteString(m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(m.Updated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sessionKey=")
	builder.WriteString(m.SessionKey)
	builder.WriteString(", ")
	builder.WriteString("from=")
	builder.WriteString(fmt.Sprintf("%v", m.From))
	builder.WriteString(", ")
	builder.WriteString("to=")
	builder.WriteString(m.To)
	builder.WriteString(", ")
	builder.WriteString("session_type=")
	builder.WriteString(fmt.Sprintf("%v", m.SessionType))
	builder.WriteString(", ")
	builder.WriteString("client_msg_id=")
	builder.WriteString(m.ClientMsgID)
	builder.WriteString(", ")
	builder.WriteString("server_msg_seq=")
	builder.WriteString(fmt.Sprintf("%v", m.ServerMsgSeq))
	builder.WriteString(", ")
	builder.WriteString("msg_type=")
	builder.WriteString(fmt.Sprintf("%v", m.MsgType))
	builder.WriteString(", ")
	builder.WriteString("msg_data=")
	builder.WriteString(m.MsgData)
	builder.WriteString(", ")
	builder.WriteString("msg_res_code=")
	builder.WriteString(fmt.Sprintf("%v", m.MsgResCode))
	builder.WriteString(", ")
	builder.WriteString("msg_feature=")
	builder.WriteString(fmt.Sprintf("%v", m.MsgFeature))
	builder.WriteString(", ")
	builder.WriteString("msg_status=")
	builder.WriteString(fmt.Sprintf("%v", m.MsgStatus))
	builder.WriteByte(')')
	return builder.String()
}

// Messages is a parsable slice of Message.
type Messages []*Message

func (m Messages) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
