server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
registry:
  etcd:
    endpoints: [ 127.0.0.1:2379 ]
    register_server_name: rpc-pushjob
kafka:
  brokers:
    - 192.168.0.164:9092
  ws_push_topic: pushUserMsg