// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/contrib/registry/etcd/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	log2 "github.com/gomicroim/gomicroim/pkg/log"
	"pushjob/internal/conf"
	"pushjob/internal/server"
	"pushjob/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger, logLogger *log2.Logger, registry *etcd.Registry) (*kratos.App, func(), error) {
	pushJobService := service.NewPushJobService()
	grpcServer := server.NewGRPCServer(confServer, pushJobService, logger)
	app := newApp(logLogger, grpcServer, registry)
	return app, func() {
	}, nil
}
