// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: api/pushjob/pushjob.proto

package pushjob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接收者类型，只需要提供三种方式即可，其他由msg-dp转换
type InternalWsPushMessage_ToType int32

const (
	InternalWsPushMessage_ReceiverTypeUnknown   InternalWsPushMessage_ToType = 0 // 未知类型，不转发
	InternalWsPushMessage_ReceiverTypeBatchUser InternalWsPushMessage_ToType = 1 // 转发给某一批用户
	InternalWsPushMessage_ReceiverTypeAllUser   InternalWsPushMessage_ToType = 2 // 转发给所有在线用户
)

// Enum value maps for InternalWsPushMessage_ToType.
var (
	InternalWsPushMessage_ToType_name = map[int32]string{
		0: "ReceiverTypeUnknown",
		1: "ReceiverTypeBatchUser",
		2: "ReceiverTypeAllUser",
	}
	InternalWsPushMessage_ToType_value = map[string]int32{
		"ReceiverTypeUnknown":   0,
		"ReceiverTypeBatchUser": 1,
		"ReceiverTypeAllUser":   2,
	}
)

func (x InternalWsPushMessage_ToType) Enum() *InternalWsPushMessage_ToType {
	p := new(InternalWsPushMessage_ToType)
	*p = x
	return p
}

func (x InternalWsPushMessage_ToType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalWsPushMessage_ToType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pushjob_pushjob_proto_enumTypes[0].Descriptor()
}

func (InternalWsPushMessage_ToType) Type() protoreflect.EnumType {
	return &file_api_pushjob_pushjob_proto_enumTypes[0]
}

func (x InternalWsPushMessage_ToType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalWsPushMessage_ToType.Descriptor instead.
func (InternalWsPushMessage_ToType) EnumDescriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{6, 0}
}

// 单推给某个用户
type SingleUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WsMsgType int32      `protobuf:"varint,2,opt,name=ws_msg_type,json=wsMsgType,proto3" json:"ws_msg_type,omitempty"`
	Data      *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SingleUserRequest) Reset() {
	*x = SingleUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleUserRequest) ProtoMessage() {}

func (x *SingleUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleUserRequest.ProtoReflect.Descriptor instead.
func (*SingleUserRequest) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{0}
}

func (x *SingleUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SingleUserRequest) GetWsMsgType() int32 {
	if x != nil {
		return x.WsMsgType
	}
	return 0
}

func (x *SingleUserRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type SingleUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SingleUserReply) Reset() {
	*x = SingleUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleUserReply) ProtoMessage() {}

func (x *SingleUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleUserReply.ProtoReflect.Descriptor instead.
func (*SingleUserReply) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{1}
}

// 推送给一批用户
type BatchUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    []int64    `protobuf:"varint,1,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WsMsgType int32      `protobuf:"varint,2,opt,name=ws_msg_type,json=wsMsgType,proto3" json:"ws_msg_type,omitempty"`
	Data      *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchUserRequest) Reset() {
	*x = BatchUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserRequest) ProtoMessage() {}

func (x *BatchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserRequest.ProtoReflect.Descriptor instead.
func (*BatchUserRequest) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{2}
}

func (x *BatchUserRequest) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *BatchUserRequest) GetWsMsgType() int32 {
	if x != nil {
		return x.WsMsgType
	}
	return 0
}

func (x *BatchUserRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchUserReply) Reset() {
	*x = BatchUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserReply) ProtoMessage() {}

func (x *BatchUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserReply.ProtoReflect.Descriptor instead.
func (*BatchUserReply) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{3}
}

// 推送给所有用户
type AllOnlineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WsMsgType       int32      `protobuf:"varint,1,opt,name=ws_msg_type,json=wsMsgType,proto3" json:"ws_msg_type,omitempty"`
	Data            *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	NeedOfflinePush bool       `protobuf:"varint,3,opt,name=needOfflinePush,proto3" json:"needOfflinePush,omitempty"` // 是否启用系统推送，true：是，false：只通过ws推送
}

func (x *AllOnlineUserReq) Reset() {
	*x = AllOnlineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllOnlineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOnlineUserReq) ProtoMessage() {}

func (x *AllOnlineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOnlineUserReq.ProtoReflect.Descriptor instead.
func (*AllOnlineUserReq) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{4}
}

func (x *AllOnlineUserReq) GetWsMsgType() int32 {
	if x != nil {
		return x.WsMsgType
	}
	return 0
}

func (x *AllOnlineUserReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AllOnlineUserReq) GetNeedOfflinePush() bool {
	if x != nil {
		return x.NeedOfflinePush
	}
	return false
}

type AllOnlineUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllOnlineUserReply) Reset() {
	*x = AllOnlineUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllOnlineUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOnlineUserReply) ProtoMessage() {}

func (x *AllOnlineUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOnlineUserReply.ProtoReflect.Descriptor instead.
func (*AllOnlineUserReply) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{5}
}

// 通过MQ发送给ws网关的消息定义
type InternalWsPushMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToType    InternalWsPushMessage_ToType `protobuf:"varint,1,opt,name=toType,proto3,enum=pushjob.InternalWsPushMessage_ToType" json:"toType,omitempty"` // 转发目标类型, ToType
	ToIds     []string                     `protobuf:"bytes,2,rep,name=toIds,proto3" json:"toIds,omitempty"`                                              // 接收者ID，SingleUser代表单个用户ID，RoomAllUser代表RoomID
	WsMsgType int32                        `protobuf:"varint,3,opt,name=wsMsgType,proto3" json:"wsMsgType,omitempty"`                                     // 类型 详见 constants.proto 中 WSMessageType 结构
	AnyData   *anypb.Any                   `protobuf:"bytes,4,opt,name=anyData,proto3" json:"anyData,omitempty"`                                          // 推送给客户端的数据。
	// 推送客户端类型，internal_message.proto/ClientType
	// ToClientType toClientType = 10;
	// 版本号过滤，仅适用于app（当ClientTypeWeb!=Web时）
	// AppVersionFilter toAppVersionFilter = 11;
	TraceId string `protobuf:"bytes,13,opt,name=traceId,proto3" json:"traceId,omitempty"` // 链路追踪使用
}

func (x *InternalWsPushMessage) Reset() {
	*x = InternalWsPushMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pushjob_pushjob_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalWsPushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalWsPushMessage) ProtoMessage() {}

func (x *InternalWsPushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_pushjob_pushjob_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalWsPushMessage.ProtoReflect.Descriptor instead.
func (*InternalWsPushMessage) Descriptor() ([]byte, []int) {
	return file_api_pushjob_pushjob_proto_rawDescGZIP(), []int{6}
}

func (x *InternalWsPushMessage) GetToType() InternalWsPushMessage_ToType {
	if x != nil {
		return x.ToType
	}
	return InternalWsPushMessage_ReceiverTypeUnknown
}

func (x *InternalWsPushMessage) GetToIds() []string {
	if x != nil {
		return x.ToIds
	}
	return nil
}

func (x *InternalWsPushMessage) GetWsMsgType() int32 {
	if x != nil {
		return x.WsMsgType
	}
	return 0
}

func (x *InternalWsPushMessage) GetAnyData() *anypb.Any {
	if x != nil {
		return x.AnyData
	}
	return nil
}

func (x *InternalWsPushMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_api_pushjob_pushjob_proto protoreflect.FileDescriptor

var file_api_pushjob_pushjob_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2f, 0x70, 0x75,
	0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x75, 0x73,
	0x68, 0x6a, 0x6f, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x76, 0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0b, 0x77, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x77, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x75, 0x0a, 0x10, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x77, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x73,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x10, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0b, 0x77, 0x73, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77,
	0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x65, 0x65, 0x64, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6e, 0x65, 0x65,
	0x64, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x75, 0x73, 0x68, 0x22, 0x14, 0x0a, 0x12,
	0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0xab, 0x02, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x57,
	0x73, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x06,
	0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x57,
	0x73, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x49, 0x64,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x61, 0x6e, 0x79, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x61, 0x6e, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x06, 0x54, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02,
	0x32, 0xe9, 0x01, 0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x4a, 0x6f, 0x62, 0x12, 0x48, 0x0a, 0x10,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x75, 0x73, 0x68,
	0x6a, 0x6f, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a,
	0x13, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x41,
	0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2e, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1d, 0x5a, 0x1b,
	0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x73, 0x68,
	0x6a, 0x6f, 0x62, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_pushjob_pushjob_proto_rawDescOnce sync.Once
	file_api_pushjob_pushjob_proto_rawDescData = file_api_pushjob_pushjob_proto_rawDesc
)

func file_api_pushjob_pushjob_proto_rawDescGZIP() []byte {
	file_api_pushjob_pushjob_proto_rawDescOnce.Do(func() {
		file_api_pushjob_pushjob_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pushjob_pushjob_proto_rawDescData)
	})
	return file_api_pushjob_pushjob_proto_rawDescData
}

var file_api_pushjob_pushjob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_pushjob_pushjob_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_pushjob_pushjob_proto_goTypes = []interface{}{
	(InternalWsPushMessage_ToType)(0), // 0: pushjob.InternalWsPushMessage.ToType
	(*SingleUserRequest)(nil),         // 1: pushjob.SingleUserRequest
	(*SingleUserReply)(nil),           // 2: pushjob.SingleUserReply
	(*BatchUserRequest)(nil),          // 3: pushjob.BatchUserRequest
	(*BatchUserReply)(nil),            // 4: pushjob.BatchUserReply
	(*AllOnlineUserReq)(nil),          // 5: pushjob.AllOnlineUserReq
	(*AllOnlineUserReply)(nil),        // 6: pushjob.AllOnlineUserReply
	(*InternalWsPushMessage)(nil),     // 7: pushjob.InternalWsPushMessage
	(*anypb.Any)(nil),                 // 8: google.protobuf.Any
}
var file_api_pushjob_pushjob_proto_depIdxs = []int32{
	8, // 0: pushjob.SingleUserRequest.data:type_name -> google.protobuf.Any
	8, // 1: pushjob.BatchUserRequest.data:type_name -> google.protobuf.Any
	8, // 2: pushjob.AllOnlineUserReq.data:type_name -> google.protobuf.Any
	0, // 3: pushjob.InternalWsPushMessage.toType:type_name -> pushjob.InternalWsPushMessage.ToType
	8, // 4: pushjob.InternalWsPushMessage.anyData:type_name -> google.protobuf.Any
	1, // 5: pushjob.PushJob.PushToSingleUser:input_type -> pushjob.SingleUserRequest
	3, // 6: pushjob.PushJob.PushToBatchUser:input_type -> pushjob.BatchUserRequest
	5, // 7: pushjob.PushJob.PushToAllOnlineUser:input_type -> pushjob.AllOnlineUserReq
	2, // 8: pushjob.PushJob.PushToSingleUser:output_type -> pushjob.SingleUserReply
	4, // 9: pushjob.PushJob.PushToBatchUser:output_type -> pushjob.BatchUserReply
	6, // 10: pushjob.PushJob.PushToAllOnlineUser:output_type -> pushjob.AllOnlineUserReply
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_pushjob_pushjob_proto_init() }
func file_api_pushjob_pushjob_proto_init() {
	if File_api_pushjob_pushjob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pushjob_pushjob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllOnlineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllOnlineUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pushjob_pushjob_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalWsPushMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pushjob_pushjob_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pushjob_pushjob_proto_goTypes,
		DependencyIndexes: file_api_pushjob_pushjob_proto_depIdxs,
		EnumInfos:         file_api_pushjob_pushjob_proto_enumTypes,
		MessageInfos:      file_api_pushjob_pushjob_proto_msgTypes,
	}.Build()
	File_api_pushjob_pushjob_proto = out.File
	file_api_pushjob_pushjob_proto_rawDesc = nil
	file_api_pushjob_pushjob_proto_goTypes = nil
	file_api_pushjob_pushjob_proto_depIdxs = nil
}
