server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: cim:coffeechat2022@tcp(mysql:3306)/coffeechat?charset=utf8mb4&parseTime=true
  redis:
    addr: redis:6379
    password: "coffeechat"
    db: 0
    read_timeout: 0.4s
    write_timeout: 0.6s
    dial_timeout: 1s
  kafka:
    brokers:
      - kafka:9092
    consumer_group: rpc-chat
    consumer_topics:
      outbox_write: msg_write_outbox
    producer_topics:
      outbox_write: msg_write_outbox
      dead: msg_write_failed
  timeline:
    grpc_addr: "timeline:9321"
registry:
  etcd:
    endpoints: [ etcd:2379 ]
    register_server_name: rpc-chat
    register_end_point: "host.docker.internal:9101"