server:
  ws:
    addr: 0.0.0.0:8000
    timeout: 1s
  server_id: auto
discover:
  etcd:
    endpoints: [etcd:2379]
  service_endpoint:
    rpc_user: rpc-user
kafka:
  brokers:
    - kafka:9092
  send_msg_topic: pushUserMsg