server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  jwt:
    access_secret: "i love im"
    refresh_secret: "u love im"
discover:
  etcd:
    endpoints: [127.0.0.1:2379]
  service_endpoint:
    rpc_chat: rpc-chat